# Generated by Django 4.2.7 on 2023-11-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='s_id',
            field=models.IntegerField(),
        ),
    ]
